# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Set up a virtual environment
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip

      - restore_cache: # Download and cache dependencies.
          key: dependency-cache-{{ checksum "requirements.txt" }}

      - run:
          name: Install dependencies
          command: |
            . venv/bin/activate
            pip install --upgrade setuptools wheel
            pip install -r requirements.txt

      - save_cache: # Special step to save the dependency cache.
          key: dependency-cache-{{ checksum "requirements.txt" }}
          paths:
            - ./venv

      - run:
          name: Run the unit tests
          command: |
            . venv/bin/activate
            pytest ./tests/unit

      - store_artifacts:
          path: htmlcov
          destination: test-reports
